name: ✨ Feature Request
description: Suggest A New Feature / Enhancement for PEND Boilerplate
title: "[FEATURE] "
labels: ["enhancement", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## ✨ Feature Request

        Thank You for Suggesting A New Feature! We Appreciate Your Contribution to Improving the PEND Boilerplate.

        **Before Submitting** : 
        - [ ] I have Searched [Existing Issues](https://github.com/jeet-khondker/pend-boilerplate/issues) & [Discussions](https://github.com/jeet-khondker/pend-boilerplate/discussions) to Ensure this hasn't been Suggested
        - [ ] I have Discussed this Idea in [GitHub Discussions](https://github.com/jeet-khondker/pend-boilerplate/discussions/new?category=ideas)
        - [ ] This Feature Aligns with the Project's Goals & Scope

  - type: dropdown
    id: module
    attributes:
      label: Module
      description: Which Module would this Feature Affect?
      options:
        - Backend (Django)
        - Frontend (NextJS)
        - Mobile (Expo)
        - Database (PostgreSQL)
        - CI / CD (GitHub Actions)
        - Docker / Infrastructure
        - Documentation
        - Scripts / Automation
        - Testing
        - Multiple Modules
        - Other
    validations:
      required: true

  - type: dropdown
    id: type
    attributes:
      label: Feature Type
      description: What Type of Feature is this?
      options:
        - New Feature - Adds New fFnctionality
        - Enhancement - Improves Existing Functionality
        - Performance - Improves Performance
        - Developer Experience - Improves Developers' Experience (DevEx)
        - Documentation - Improves Documentation
        - Testing - Improves Test Coverage
        - Security - Enhances Security
        - Accessibility - Improves Accessibility
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How Important is this Feature?
      options:
        - 🔴 High - Critical for Project Success
        - 🟠 Medium - Important But Not Blocking
        - 🟢 Low - Nice to have
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Describe the Problem / Pain Point this Feature would Solve
      placeholder: |
        Example : As a Developer, I find it difficult to debug Authentication Issues because there's no Centralized Logging for Authentication (auth) Events. This makes Troubleshooting Time-Consuming & Inefficient.
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the Solution You'd like to See Implemented
      placeholder: |
        Example: Add a Centralized Authentication Logging System that captures : 
        - Login Attempts (Successful & Failed)
        - Token Refresh Events
        - Logout Events
        - Include Timestamp, User ID, IP Address & User Agent
        - Store Logs in a Dedicated `auth_logs` Table
        - Provide a Dashboard View in the Administrator Panel
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe Alternative Solutions / Features You've Considered
      placeholder: |
        Example: 
        1. Using Django's Built-In Logging - But it doesn't provide Structured Data
        2. 3rd Party Service like Sentry - But adds External Dependency & Cost
        3. File-Based Logging - But Harder to Query & Analyze

  - type: textarea
    id: benefits
    attributes:
      label: Benefits
      description: What are the Benefits of Implementing this Feature?
      placeholder: |
        - Faster Debugging of Authentication Issues
        - Better Security Monitoring
        - Compliance with Audit Requirements
        - Improved User Support
    validations:
      required: true

  - type: textarea
    id: drawbacks
    attributes:
      label: Potential Drawbacks
      description: Are there Any Potential Downsides / Concerns?
      placeholder: |
        - Additional Database Storage Required
        - Slight Performance Impact on Authentication Ooperations
        - Privacy Considerations for Storing IP Addresses

  - type: textarea
    id: implementation
    attributes:
      label: Implementation Ideas
      description: If You have Specific Implementation Ideas, Share them here
      placeholder: |
        1. Create New Django Application : `auth_logging`
        2. Add Model : `AuthLog` with Fields for Event Type, User, Timestamp, Metadata
        3. Create Middleware to Capture Authentication Events
        4. Add Administrator Interface for Viewing Logs
        5. Include Filtering & Search Capabilities

  - type: textarea
    id: examples
    attributes:
      label: Examples / References
      description: Links to Similar Implementations / Examples from other Projects
      placeholder: |
        - `django-auditlog` : https://github.com/jazzband/django-auditlog
        - NextJS Logging Example : https://example.com

  - type: textarea
    id: mockups
    attributes:
      label: Mockups / Diagrams
      description: |
        If Applicable, Add Mockups, Wireframes / Diagrams.
        Tip : You can Drag & Drop Images directly into this Field.

  - type: dropdown
    id: breaking
    attributes:
      label: Breaking Changes
      description: Would this Feature introduce Breaking Changes?
      options:
        - "No - Fully Backward Compatible"
        - "Yes - Requires Migration"
        - "Yes - Requires Configuration Changes"
        - "Yes - Changes Existing Behavior"
        - "Not Sure"
    validations:
      required: true

  - type: textarea
    id: documentation
    attributes:
      label: Documentation Requirements
      description: What Documentation Need to be Created / Updated?
      placeholder: |
        - Add Guide to documentation/backend/authentication-logging.md
        - Update `CHANGELOG.md`
        - Update `backend/README.md`
        - Add Configuration Examples to `.env.example`

  - type: textarea
    id: testing
    attributes:
      label: Testing Requirements
      description: What Testing would be Needed for this Feature?
      placeholder: |
        - Unit Tests for `AuthLog` Model
        - Integration Tests for Logging Middleware
        - E2E Tests for Administrator Interface
        - Performance Tests for Authentication Operations with Logging

  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      description: What Criteria must be met for this Feature to be Considered Complete?
      placeholder: |
        - [ ] Authentication Events are Logged to Database
        - [ ] Administrator Interface displays Logs with Filtering
        - [ ] Performance Impact is Less Than 5 Milliseconds Per Request
        - [ ] Documentation is Complete
        - [ ] Tests have 90%+ Coverage
        - [ ] No Breaking Changes to Existing Authentication Flow

  - type: textarea
    id: timeline
    attributes:
      label: Suggested Timeline
      description: When would You like to see this Implemented?
      placeholder: |
        - Next Minor Release (v1.1.0)
        - Next Major Release (v2.0.0)
        - No Rush, When Convenient

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would You like to Contribute to this Feature?
      options:
        - label: I am willing to Submit A Pull Request to implement this Feature
          required: false
        - label: I can Help with Documentation for this Feature
          required: false
        - label: I can Help with Testing this Feature
          required: false
        - label: I can Help with Design / Mockups for this Feature
          required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-Submission Checklist
      description: Please Confirm the Following Before Submitting the Issue
      options:
        - label: I have Provided All the Required Information above
          required: true
        - label: I have Discussed this Idea in GitHub Discussions first
          required: false
        - label: This Feature Aligns with the Project's Mission & Scope
          required: true
